CREATE TABLE `money_forward_billings_attribute_data`
(
  `billing_number`                                           varchar(10) NOT NULL,
  `id`                                                       varchar(10) NOT NULL,
  `department_id`                                            varchar(30) NOT NULL,
  `type`                                                     varchar(10) NOT NULL,
  `pdf_url`                                                  varchar(255) NOT NULL,
  `operator_id`                                              varchar(10) DEFAULT NULL,
  `partner_id`                                               varchar(10) DEFAULT NULL,
  `member_id`                                                varchar(10) DEFAULT NULL,
  `member_name`                                              varchar(255) DEFAULT NULL,  
  `partner_name`                                             varchar(255) DEFAULT NULL,
  `partner_name_suffix`                                      varchar(255) DEFAULT NULL,
  `partner_detail`                                           varchar(255) DEFAULT NULL,
  `office_name`                                              varchar(255) DEFAULT NULL,
  `office_detail`                                            varchar(255) DEFAULT NULL,
  `title`                                                    varchar(100) DEFAULT NULL,
  `excise_price`                                             varchar(30) DEFAULT NULL,
  `excise_price_of_five_percent`                             varchar(30) DEFAULT NULL,
  `excise_price_of_eight_percent`                            varchar(30) DEFAULT NULL,
  `excise_price_of_eight_percent_as_reduced_tax_rate`        varchar(30) DEFAULT NULL,
  `excise_price_of_ten_percent`                              varchar(30) DEFAULT NULL,
  `subtotal`                                                 varchar(30) DEFAULT NULL,
  `subtotal_of_untaxable_excise`                             varchar(30) DEFAULT NULL,
  `subtotal_of_non_taxable_excise`                           varchar(30) DEFAULT NULL,
  `subtotal_of_tax_exemption_excise`                         varchar(30) DEFAULT NULL,
  `subtotal_of_five_percent_excise`                          varchar(30) DEFAULT NULL,
  `subtotal_of_eight_percent_excise`                         varchar(30) DEFAULT NULL,
  `subtotal_of_eight_percent_as_reduced_tax_rate_excise`     varchar(30) DEFAULT NULL,
  `subtotal_of_ten_percent_excise`                           varchar(30) DEFAULT NULL,
  `memo`                                                     varchar(255) DEFAULT NULL,
  `payment_condition`                                        varchar(30) DEFAULT NULL,
  `total_price`                                              varchar(30) DEFAULT NULL,
  `billing_date`                                             varchar(10) DEFAULT NULL,
  `due_date`                                                 varchar(10) DEFAULT NULL,
  `sales_date`                                               varchar(10) DEFAULT NULL,
  `billing_number`                                           varchar(30) DEFAULT NULL,
  `note`                                                     varchar(255) DEFAULT NULL,
  `document_name`                                            varchar(255) DEFAULT NULL,
  `payment_status`                                           varchar(30) DEFAULT NULL,
  `email_status`                                             varchar(30) DEFAULT NULL,
  `posting_status`                                           varchar(30) DEFAULT NULL,
  `created_at`                                               varchar(10) DEFAULT NULL,
  `updated_at`                                               varchar(10) DEFAULT NULL,
  `is_downloaded`                                            tinyint(1) DEFAULT NULL,
  `is_locked`                                                tinyint(1) DEFAULT NULL,
  `deduct_price`                                             varchar(30) DEFAULT NULL,

  PRIMARY KEY (`billing_number`, `id`),
  
  CONSTRAINT `MoneyForwardBillingsAttributesData_fk` FOREIGN KEY (`billing_number`) REFERENCES `freee_billings_billings_data` (`billing_number`)

) ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4;